spring:
  application:
    name: FR-Blog
  cache:
    cache-names: ehcache
    ehcache:
      config: ehcache.xml
  devtools:
    restart:
      enabled: true
  freemarker:
    enabled: true
    cache: false
    suffix: .ftl
    charset: utf-8
    ######## todo 发布版本时同步更新 ***-prod.yml ########
    view-names: index,
                error,
                userlogin,
                adminlogin,
                register,
                article,
                posts,
                chat,
                resume,
                admin/index,
                admin/userlogin,
                admin/blogadd,
                admin/blog_manage,
                admin/blog_modify,
                admin/admin_user_manage,
                admin/admin_user_pwd_modify,
                admin/resume_modify,
                admin/wx_open_users_manage
    #####################################
    content-type: text/html
    allow-request-override: true
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
    template-loader-path: classpath:/templates/
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
        fixed:
          enabled: true
          paths: /js/lib
          version: v12
    static-locations: classpath:/static/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/public/
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: zpx1121.
    url: jdbc:mysql://118.178.178.110:3306/fsblog?useUnicode=true&characterEncoding=utf8

    driverClassName: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 50
      minimum-idle: 5
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialize: false
    continue-on-error: true
    jpa:
      hibernate:
        ddl-auto: none

http:
  port: 8080

server:
  port: 4433
  max-http-header-size: 8192
  compression:
      min-response-size: 512
      enabled: true
      mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg
#  ssl:
#      key-store: classpath:4612993_www.zpxblogs.com.pfx
#      key-store-password: dGRO2JXJ
#      key-store-type: PKCS12
  tomcat:
        maxThreads: 12
        minSpareThreads: 3
        accesslog:
#          线上环境
#          directory: /docker/data/logs/app
          directory: /Users/zpx/Desktop/工作/log/app/
          pattern: combined
          enabled: true
  session:
    cookie:
      max-age: -1

logging:
    config: classpath:log4j2.xml

mybatis:
    type-aliases-package: me.zbl.fullstack.entity
    mapper-locations: classpath:mapping/*.xml

file:
#    线上地址
#  uploadFolder: /docker/data/temp/
#  本地地址
  uploadFolder: /Users/zpx/Desktop/工作/log/app/img/
wxOpen:
    appid: wxd494462d567edae8
    AppSecret: d84f6cb7e4009d62fce444e99e361a75

tengxunyun:
    oss:
      secretId: AKIDA5mESRjr42pwoQrysa6QK2WlocbLQ55p
      secretKey: h8KL8gz3sRlpllX4MOAhy2sTpwEQN5f0
      bucket: zpxblogs-1259581391
      PathKey: /Blogs/image/


